### ISSUE TITLE
Config flow fails with "could not be loaded"

### ISSUE THREAD

**Issue by cwjohnston** [natekspencer/hacs-pura#13]
I've installed the integration via HACS but cannot complete the config flow. I'm never prompted for credentials, it just spins for a while before failing with this error:

```
Error
Config flow could not be loaded: <html>
 <head><title>504 Gateway Time-out</title></head>
 <body>
 <center><h1>504 Gateway Time-out</h1></center>
 <hr><center>nginx</center>
 </body>
 </html>
```

I was unable to find any related log entries in Home Assistant Core. I'm guessing this gateway timeout coming from the Pura API, but I'm not sure. Any suggestions?

**Comment by natekspencer** [comment]
This is an error from Home Assistant since it wouldn't have tried to do anything with Pura yet.

When you first try to set up an integration, Home Assistant attempts to install the required Python packages and dependencies from pypi. It's possible there was a timeout during that process resulting in this error. There also might be a version conflict, but I usually have seen an "unknown error" in that scenario. Also, if you have any add-ons installed aimed at protecting network activity, that could potentially be causing issues.

**Comment by cwjohnston** [comment]
Thanks for clarifying where the error was likely occurring. 

After applying pending OS and HA upgrades and rebooting the host, setup runs successfully!
